spring.application.name=cityapi
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

kakao.api.key=${KAKAO_API_KEY}
seoul.api.key=${SEOUL_API_KEY}



