name: Deploy to EC2  # GitHub Actions의 워크플로 이름

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions에서 사용할 가상 환경 (Ubuntu 최신 버전)

    steps:
      - name: Checkout repository  # GitHub 리포지토리 코드 가져오기
        uses: actions/checkout@v3

      - name: Set up JDK 17  # Java 17 환경 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build oauthlogin with Gradle  # oauthlogin 프로젝트 빌드 (테스트 제외)
        run: |
          cd back/oauthlogin
          ./gradlew clean build -x test 

      - name: Login to Docker Hub  # Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push oauthlogin Docker image  # Docker 이미지 빌드 및 Docker Hub로 푸시
        run: |
          cd back/oauthlogin
          docker build --no-cache -t rio8972/oauthlogin:latest .
          docker push rio8972/oauthlogin:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}  # Base64 없이 원본 SSH 키 사용
          port: 22
          script: |
            # EC2에서 Docker Hub 로그인
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            cd docker-compose
            docker-compose pull
            docker-compose down
            docker-compose up -d —-force-recreate  # 강제로 새로운 컨테이너로 재생성
